{"uuid": "0ab297b0-c78f-4e2a-94a9-a842588b43d3", "children": ["ea0a6962-2b38-4958-a75f-3532c27570ab"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: Could not create a session: The Safari instance is already paired with another WebDriver session.\n\n", "trace": "  File \"/Users/silviaho/PycharmProjects/SampleProject/venv/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/silviaho/PycharmProjects/SampleProject/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1124, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/silviaho/PycharmProjects/SampleProject/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 921, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/silviaho/PycharmProjects/SampleProject2/Testcase/conftest.py\", line 16, in init_driver\n    driver = webdriver.Safari()\n  File \"/Users/silviaho/PycharmProjects/SampleProject/venv/lib/python3.8/site-packages/selenium/webdriver/safari/webdriver.py\", line 62, in __init__\n    RemoteWebDriver.__init__(\n  File \"/Users/silviaho/PycharmProjects/SampleProject/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/silviaho/PycharmProjects/SampleProject/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/Users/silviaho/PycharmProjects/SampleProject/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/silviaho/PycharmProjects/SampleProject/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1604933837835, "stop": 1604933838863}], "start": 1604933837835, "stop": 1604933838962}